# Generated by Django 2.2 on 2019-07-15 13:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(70000000000), django.core.validators.MaxValueValidator(79999999999)])),
                ('code', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('brand', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('category', models.CharField(choices=[('shoes', 'SHOES')], max_length=100)),
                ('subsubcategory', models.CharField(choices=[('classic', (('oxfords', 'OXFORDS'), ('derby', 'DERBY'), ('lufers', 'LUFERS'), ('monkey', 'MONKEY'), ('brogy', 'BROGY'), ('forth_brogy', 'FORTH_BROGY'), ('half_brogy', 'HALF_BROGY'))), ('boots', (('chakka', 'CHAKKA'), ('desert', 'DESERT'), ('chelsi', 'CHELSI'))), ('casual', (('topsiders', 'TOPSIDERS'), ('mokasins', 'MOKASINS'), ('espadrils', 'ESPADRILS'), ('sandals', 'SANDALS'))), ('sport', (('cross', 'CROSS'), ('football', 'FOOTBALL'), ('basketball', 'BASKETBALL'), ('tennis', 'TENNIS'), ('run', 'RUN'), ('keds', 'KEDS')))], max_length=100)),
                ('top_material', models.CharField(blank=True, choices=[('nat_skin', 'NAT_SKIN'), ('no_nat_skin', 'NO_NAT_SKIN'), ('tecstyle', 'TECSTYLE'), ('nat_nubuk', 'NAT_NUBUK'), ('nat_zamsh', 'NAT_ZAMSH'), ('fetr', 'FETR'), ('polyester', 'POLYESTER'), ('neylon', 'NEYLON'), ('sherst', 'SHERST'), ('no_nat_zamsh', 'NO_NAT_ZAMSH'), ('no_nat_nubuk', 'NO_NAT_NUBUK'), ('polyuretan', 'POLYURETAN'), ('spiloc', 'SPILOC'), ('cotton', 'COTTON')], max_length=100)),
                ('inside_material', models.CharField(blank=True, choices=[('bayka', 'BAYKA'), ('sherst', 'SHERST'), ('nat_skin', 'NAT_SKIN'), ('tecstyle', 'TECSTYLE'), ('nat_meh', 'NAT_meh'), ('no_nat_nubuk', 'NO_NAT_NUBUK'), ('no_nat_meh', 'NO_NAT_meh'), ('no_nat_skin', 'NO_NAT_SKIN'), ('without', 'WITHOUT'), ('sherst_meh', 'SHERST_MEH'), ('polyester', 'POLYESTER')], max_length=100)),
                ('bottom_material', models.CharField(blank=True, choices=[('rezina', 'REZINA'), ('polyuretan', 'POLYURETAN'), ('kozhvolon', 'KOZHVOLON'), ('no_nat', 'NO_NAT'), ('polymer', 'POLYMER'), ('thermoplastic_rezina', 'THERMOPLASTIC_REZINA'), ('thermopolyuretan', 'THERMOPOLYURETAN'), ('filon', 'FILON'), ('thermoelast', 'THERMOELAST'), ('micropore', 'MICROPORE')], max_length=100)),
                ('step_material', models.CharField(blank=True, choices=[('tecstyle', 'TECSTYLE'), ('nat_skin', 'NAT_SKIN'), ('nat_meh', 'NAT_meh'), ('no_nat_meh', 'NO_NAT_meh'), ('bayka', 'BAYKA'), ('sherst', 'SHERST'), ('sherst_meh', 'SHERST_MEH'), ('polyester', 'POLYESTER'), ('no_nat_skin', 'NO_NAT_SKIN'), ('no_nat_zamsh', 'NO_NAT_ZAMSH'), ('cotton', 'COTTON')], max_length=100)),
                ('country', models.CharField(blank=True, choices=[('thailand', 'THAILAND'), ('china', 'CHINA'), ('russia', 'RUSSIA'), ('portugal', 'PORTUGAL'), ('turkish', 'TURKISH'), ('vietnam', 'VIETNAM'), ('india', 'INDIA'), ('germany', 'GERMANY'), ('rumany', 'RUMANY'), ('italy', 'ITALY'), ('indonize', 'INDONIZE'), ('spain', 'SPAIN')], max_length=100)),
                ('season', models.CharField(choices=[('winter', 'WINTER'), ('summer', 'SUMMER'), ('autumn_spring', 'AUTUMN_SPRING'), ('demiseason', 'DEMISEASON'), ('beach', 'BEACH'), ('multi', 'MULTI')], max_length=100)),
                ('color', models.CharField(choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('white', 'WHITE'), ('red', 'RED'), ('blue', 'BLUE'), ('cyan', 'CYAN'), ('beige', 'BEIGE'), ('grey', 'GREY'), ('violet', 'VIOLET'), ('rose', 'ROSE'), ('green', 'GREEN'), ('yellow', 'YELLOW'), ('orange', 'ORANGE')], max_length=100)),
                ('zip_type', models.CharField(blank=True, choices=[('shnirky', 'SHNURKY'), ('lipuchky', 'LIPUCHKY'), ('without', 'WITHOUT'), ('zip', 'ZIP')], max_length=100)),
                ('sport_type', models.CharField(blank=True, choices=[('sport_style', 'SPORT_STYLE'), ('run', 'RUN'), ('football', 'FOOTBALL'), ('training', 'TRAINING'), ('tennis', 'TENNIS'), ('basketball', 'BASKETBALL'), ('voleyball', 'VOLEYBALL'), ('zal', 'ZAL')], max_length=100)),
                ('image_main', models.URLField()),
                ('image_1', models.URLField()),
                ('image_2', models.URLField()),
                ('image_3', models.URLField()),
                ('image_4', models.URLField()),
                ('size36_qua', models.IntegerField(default=0)),
                ('size365_qua', models.IntegerField(default=0)),
                ('size37_qua', models.IntegerField(default=0)),
                ('size375_qua', models.IntegerField(default=0)),
                ('size38_qua', models.IntegerField(default=0)),
                ('size385_qua', models.IntegerField(default=0)),
                ('size39_qua', models.IntegerField(default=0)),
                ('size395_qua', models.IntegerField(default=0)),
                ('size40_qua', models.IntegerField(default=0)),
                ('size405_qua', models.IntegerField(default=0)),
                ('size41_qua', models.IntegerField(default=0)),
                ('size415_qua', models.IntegerField(default=0)),
                ('size42_qua', models.IntegerField(default=0)),
                ('size425_qua', models.IntegerField(default=0)),
                ('size43_qua', models.IntegerField(default=0)),
                ('size435_qua', models.IntegerField(default=0)),
                ('size44_qua', models.IntegerField(default=0)),
                ('size445_qua', models.IntegerField(default=0)),
                ('size45_qua', models.IntegerField(default=0)),
                ('size455_qua', models.IntegerField(default=0)),
                ('size46_qua', models.IntegerField(default=0)),
                ('size465_qua', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('shoes_size', models.CharField(blank=True, choices=[('36', '36'), ('36.5', '36.5'), ('37', '37'), ('37.5', '37.5'), ('38', '38'), ('38.5', '38.5'), ('39', '39'), ('39.5', '39.5'), ('40', '40'), ('40.5', '40.5'), ('41', '41'), ('41.5', '41.5'), ('42', '42'), ('42.5', '42.5'), ('43', '43'), ('43.5', '43.5'), ('44', '44'), ('44.5', '44.5'), ('45', '45'), ('45.5', '45.5'), ('46', '46'), ('46.5', '46.5')], max_length=4)),
                ('bought', models.ManyToManyField(blank=True, related_name='bought', to='registration.ShoesItem')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to='registration.ShoesItem')),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to='registration.ShoesItem')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='registration.ShoesItem')),
                ('saw', models.ManyToManyField(blank=True, related_name='saw', to='registration.ShoesItem')),
            ],
        ),
    ]
