# Generated by Django 2.2 on 2019-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190715_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesitem',
            name='category',
            field=models.CharField(blank=True, choices=[('shoes', 'SHOES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shoesitem',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('unisex', 'UNISEX')], max_length=100),
        ),
    ]
