# Generated by Django 2.2 on 2019-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190715_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesitem',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('white', 'WHITE'), ('red', 'RED'), ('blue', 'BLUE'), ('cyan', 'CYAN'), ('beige', 'BEIGE'), ('grey', 'GREY'), ('violet', 'VIOLET'), ('rose', 'ROSE'), ('green', 'GREEN'), ('yellow', 'YELLOW'), ('orange', 'ORANGE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shoesitem',
            name='image_1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoesitem',
            name='image_2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoesitem',
            name='image_3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoesitem',
            name='image_4',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoesitem',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'WINTER'), ('summer', 'SUMMER'), ('autumn_spring', 'AUTUMN_SPRING'), ('demiseason', 'DEMISEASON'), ('beach', 'BEACH'), ('multi', 'MULTI')], max_length=100),
        ),
    ]
